### ISSUE TITLE
Proton pass not working with keyboard

### ISSUE THREAD

**Issue by PnPost** [futo-org/android-keyboard#1247]
### What happened?

When using the keyboard proton pass does nog open in the browser when entering a password field. Changing my keyboard back to gboard and opening the browser fixes this. 

![Image](https://github.com/user-attachments/assets/f695cfcd-e37e-4f01-bebc-06f5f97c4db1)
![Image](https://github.com/user-attachments/assets/125b0c8b-d5f1-405c-8389-e57cf2ecbc43)

### Keyboard Version

0.1.12

**Comment by Zvonimir-FUTO** [comment]
Should be fixed on the latest version.

**Comment by Forage** [comment]
> Should be fixed on the latest version.

If by latest version you mean 0.1.25, I'm afraid I have to disappoint you. I still have the same issue.

**Comment by abb128** [comment]
Do you have the suggestion bar disabled?

**Comment by Forage** [comment]
The suggestion bar is enabled but the "inline autofill" option is disabled.

**Comment by abb128** [comment]
You'll have to enable both to see the password manager suggestions, if it's disabled then it won't show

**Comment by Forage** [comment]
That's the thing, I expect the regular pop-up to show when disabling the inline autofill. As shown in the second screen capture of the initial issue message. That's the reason I disabled the inline option.
You are saying using the suggestion bar is the only option?

**Comment by abb128** [comment]
Unfortunately yes, unless your password manager has an option to disable inline autofill (e.g. Bitwarden does)

We implement a method called `onInlineSuggestionsResponse` which is documented as follows
> Return value: Whether the IME will use and render the inline suggestions.

We correctly return `false` when the inline autofill option is disabled, so this should indicate to the framework that inline won't be rendered and that the password manager should fall back to the popup. But apparently it doesn't work, I don't know why and I'm not sure that we can do anything about it

**Comment by abb128** [comment]
I took another look and returning null in `createInlineSuggestionsRequest` actually seems to work, so this should be fixed in the next version

**Comment by Forage** [comment]
> I took another look and returning null in `createInlineSuggestionsRequest` actually seems to work, so this should be fixed in the next version

Great news, thank you.

**Comment by sohaibology** [comment]
I tried looking for an open issue but there wasn't one so just pinging here. My inline suggestions take ages to show up when on a field and other times just doesn't at all. I've tried reinstalling everything but no luck. Any one got a solution? Tried on both release and nightly with no luck. Please advise. 

![Screenshot_20251216_231207_Brave - Beta.png](https://github.com/user-attachments/assets/0c44eb4b-5728-4d66-894b-504ac03e035b)

**Comment by Forage** [comment]
> I tried looking for an open issue but there wasn't one so just pinging here.

You could and should have just created a new issue instead. This issue has been fixed (for me) and closed.
Yours is a different and therefore a new issue.
