### ISSUE TITLE
Enter key does not properly turn into search/accept on some forms

### ISSUE THREAD

**Issue by xicor333** [futo-org/android-keyboard#1316]
### What happened?

I just started using futo, and I noticed that when I'm using the Google search bar , the enter button remains a return key press rather than an accept or search.

### Keyboard Version

0.1.24.2

### Text field info

Google search bar on pixel 7a

https://github.com/user-attachments/assets/b982abcf-3077-49d3-abfb-e422a7d53df9

https://github.com/user-attachments/assets/a0d8d9c4-eedb-40cc-beca-514081a52dfd

**Comment by A-Table** [comment]
This has been solved in nightly: https://github.com/futo-org/android-keyboard/issues/1213#issuecomment-2827551898

**Comment by micahdas** [comment]
Is there a new release with this fix? I am on the latest prod release and still experience this

**Comment by xicor333** [comment]
I've just moved to the nightly

**Comment by KennethSJD** [comment]
Still experiencing this, is there an ETA on the prod release for this bug fix?

**Comment by Zvonimir-FUTO** [comment]
Fixed in v0.1.25.

**Comment by nielsegberts** [comment]
Thanks!

The play store update came through for me today, I can confirm this is now fixed.

**Comment by zenwav** [comment]
> Fixed in v0.1.25.

@Zvonimir-FUTO , I'm still facing this issue in ConnectBot, an SSH client app. However, the Enter key works correctly on Gboard.

https://github.com/user-attachments/assets/a4630542-77f7-4872-9849-6524cf28cfda

**Comment by Zvonimir-FUTO** [comment]
@zenwav can you please open a separate issue for this? Could also open debug info from actions (it's hidden at the bottom) and screenshot that as well?
