### ISSUE TITLE
Bug: Parenthesis are switched in RTL languages

### ISSUE THREAD

**Issue by Yuvalg1** [futo-org/android-keyboard#1463]
### Reproduction steps

1. Open Futo Keyboard App
2. Click the 'Try typing here...' text input.
3. Open parenthesis, write something in Hebrew and close parenthesis.

It reproduces with (), [], {}, <>.

### Actual result

)אבג(

### Expected result

(אבג)

### Keyboard Version

0.1.25

### Which android version are you using?

Android 16

### Which device are you using?

Google Pixel 7 Pro

### Which operating system are you using?

Stock Android

**Comment by Zvonimir-FUTO** [comment]
Just to confirm the issue is that when you enter `{` you get `}` ? 
I don't know Hebrew so I'm trying to understand it better.

**Comment by Yuvalg1** [comment]
Sorry for the inaccuracy, I meant the parenthesis are reversed. Instead of
()
I get
)(
and it happens on all 4 types of brackets.
When I checked the other types of brackets I changed it partially and it is my mistake.
I'll edit the expected result to be correct.

**Comment by Zvonimir-FUTO** [comment]
Fixed in v0.1.27

**Comment by s11s11** [comment]
I am still having this issue in v0.1.27, on my Google Pixel 7a.
@Yuvalg1 Does it work for you now?

**Comment by Yuvalg1** [comment]
@s11s11 After the update it still doesn't work

**Comment by BlueElectivire** [comment]
i don't experience this on 0.1.28 (and did in previous versions), i assume this has been fixed

**Comment by Zvonimir-FUTO** [comment]
@s11s11 & @Yuvalg1 can you guys confirm as well?

**Comment by s11s11** [comment]
Works for me now in 0.1.28. Thanks!

**Comment by Zvonimir-FUTO** [comment]
Thank you guys for confirmation. Closing this one :)
