### ISSUE TITLE
Bug: Estonian QWERTY layout does not include common Estonian letters

### ISSUE THREAD

**Issue by minosimo** [futo-org/android-keyboard#1672]
### Reproduction steps

Set keyboard layout to Estonian (QWERTY)
Long press a, u, o, s, z

### Actual result

Letters ä, ü, ö, õ, š, and ž are missing. 
It appears to be showing the "misc" letters from the [locale](https://github.com/minosimo/android-keyboard/blob/master/tools/make-keyboard-text-py/locales/et.json), rather than the "morekeys" letters.

### Expected result

Letters ä, ü, ö, õ, š, and ž are present.

### Keyboard Version

0.1.24.2

### Which android version are you using?

Android 15

### Which device are you using?

Google Pixel 8 

### Which operating system are you using?

CalyxOS

**Comment by Zvonimir-FUTO** [comment]
Please update to the latest version v0.1.26.1. This should be fixed already.

**Comment by minosimo** [comment]
Updated to 0.1.26.1, the letters are still not in longpress.

<img width="120"  alt="Image" src="https://github.com/user-attachments/assets/4a355369-c2de-4b6f-9d12-46d67992b208" />

**Comment by abb128** [comment]
Please go to Keyboard & Typing -> Long-Press Keys & Spacebar and click Reset to default on Layout of long-press keys

**Comment by minosimo** [comment]
Super, sorry for the trouble :)
