### ISSUE TITLE
Shift-Drag Selection Doesn't Work with Shift-Capitalization

### ISSUE THREAD

**Issue by DavidBevi** [futo-org/android-keyboard#177]
| Action | FUTO | Gboard | Heliboard |
|-|-|-|-|
| Drag finger on spacebar </br>to **move the cursor** | **☑️ Yes** | ☑️ Yes | ☑️ Yes |
| Tap `Shift`, </br>drag finger on spacebar </br> to **select text** | **☑️ Yes** | ❌ No | ❌ No |

I'm grateful for this addition, but if I select some text using this feature the capitalization of the selection via tapping `shift` doesn't work.

`v0.1.22-playstore`

**Comment by dean-futo** [comment]
@DavidBevi I can't seem to reproduce this. Will you please include a video?

**Comment by DavidBevi** [comment]
https://github.com/user-attachments/assets/21cad714-cfc5-4695-b1da-f1d6cd422871

**Comment by dean-futo** [comment]
This has been fixed in the latest 0.1.24 update.

**Comment by DavidBevi** [comment]
I still have the issue on 0.1.24.

I don't want to look like it's fundamental to me, I just want to contribute, and I'm available for deeper tests if you tell me what to do.

https://github.com/user-attachments/assets/7ac8b034-5815-4641-98ba-86c7abe6c787
